service:
  name: hello-ts-test-tom

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  region: us-west-1
  memorySize: 128
  timeout: 5
  environment:
    amiboTable:
      'Fn::ImportValue': ${self:custom.stage}-AmiboTableName
    amiboUserPoolId:
      'Fn::ImportValue': ${self:custom.stage}-AmiboUserPoolId

functions:
  tsHelloFunc:
    handler: handler.helloTsFunc
    events:
      - http:
          method: get
          path: hello

  jsAddFunc:
    handler: jsadd.addus
    events:
      - http:
          path: math/js-add
          method: post
          cors: true

  tsAddFunc:
    handler: tsadd.tsAddUs
    events:
      - http:
          path: math/ts-add
          method: post
          cors: true
