service:
  name: hello-ts-test-tom-v2-1

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  region: us-west-1
  memorySize: 128
  timeout: 5

functions:
  tsHelloFunc:
    handler: handler.helloTsFunc
    events:
      - http:
          method: get
          path: hello

  jsAddFunc:
    handler: jsadd.addus
    events:
      - http:
          path: math/js-add
          method: post
          cors: true

  tsAddFunc:
    handler: tsadd.tsAddUs
    events:
      - http:
          path: math/ts-add
          method: post
          cors: true
