  Resources:
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "LambdaInvokePolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "arn:aws:${self:custom.region}:*:function:${self:service}-${self:custom.stage}-graphql"
                    - "arn:aws:${self:custom.region}:*:function:${self:service}-${self:custom.stage}-graphql:*"

