Resources:
  tomAttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
  tomAttachmentsBucketDest:
    Type: AWS::S3::Bucket
    Properties:
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

# Print out the name of the bucket that is created
Outputs:
  TomPhotos2Key:
    Value:
      Ref: tomAttachmentsBucket
    Export:
      Name: ${self:custom.stage}-tom-photos
  TomPhotos2destKey:
    Value:
      Ref: tomAttachmentsBucketDest
    Export:
      Name: ${self:custom.stage}-tom-photos-dest